// eslint-disable-next-line import/no-anonymous-default-export
export default {
    // Sign In
    SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
    SIGN_IN_SUCCEEDED: 'SIGN_IN_SUCCEEDED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    // Sign Out
    SIGN_OUT_REQUESTED: 'SIGN_OUT_REQUESTED',
    SIGN_OUT_SUCCEEDED: 'SIGN_OUT_SUCCEEDED',
    SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
    // Sign Up
    SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED',
    SIGN_UP_SUCCEEDED: 'SIGN_UP_SUCCEEDED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    // Get current user
    GET_CURRENT_REQUESTED: "GET_CURRENT_REQUESTED",
    GET_CURRENT_SUCCEEDED: "GET_CURRENT_SUCCEEDED",
    GET_CURRENT_FAILED: "GET_CURRENT_FAILED",
    // Set User State
    SET_USER: 'SET_USER',
    CLEAR_USER: 'CLEAR_USER',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    CLEAR_USER_TOKEN: 'CLEAR_USER_TOKEN',
    // Update user - update password
    UPDATE_USER_REQUESTED: 'UPDATE_USER_REQUESTED',
    UPDATE_USER_SUCCEEDED: 'UPDATE_USER_SUCCEEDED',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
    CHANGE_USER_PASSWORD_REQUESTED: 'CHANGE_USER_PASSWORD_REQUESTED',
    CHANGE_USER_PASSWORD_SUCCEEDED: 'CHANGE_USER_PASSWORD_SUCCEEDED',
    CHANGE_USER_PASSWORD_FAILED: 'CHANGE_USER_PASSWORD_FAILED',
    // Get User
    GET_USER_REQUESTED: 'GET_USER_REQUESTED',
    GET_USER_SUCCEEDED: 'GET_USER_SUCCEEDED',
    GET_USER_FAILED: 'GET_USER_FAILED',


};
