// eslint-disable-next-line import/no-anonymous-default-export
export default {
    // Sign In
    SIGN_IN_SUCCEEDED: 'SIGN_IN_SUCCEEDED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    // Sign Out
    SIGN_OUT_SUCCEEDED: 'SIGN_OUT_SUCCEEDED',
    SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
    // Sign Up
    SIGN_UP_SUCCEEDED: 'SIGN_UP_SUCCEEDED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    // Get current user
    GET_CURRENT_SUCCEEDED: "GET_CURRENT_SUCCEEDED",
    GET_CURRENT_FAILED: "GET_CURRENT_FAILED",
    // delete user
    DELETE_USER_SUCCEEDED: "DELETE_USER_SUCCEEDED",
    DELETE_USER_FAILED: "DELETE_USER_FAILED",
    // Set User State
    SET_USER: 'SET_USER',
    CLEAR_USER_TOKEN: 'CLEAR_USER_TOKEN',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    //Get Product 
    GET_PRODUCT_SUCCEEDED: 'GET_PRODUCT_SUCCEEDED',
    GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED',
    // Delete Product
    DELETE_PRODUCTS_SUCCEEDED: "DELETE_PRODUCTS_SUCCEEDED",
    DELETE_PRODUCTs_FAILED: "DELETE_PRODUCTS_FAILED",

    SAVE_CHANGES_FAILED:"SAVE_CHANGES_FAILED",

    ADD_PRODUCT_TO_CART:"ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART:"REMOVE_PRODUCT_FROM_CART"
    }
    

