// eslint-disable-next-line import/no-anonymous-default-export
export default {
    // Sign In
    SIGN_IN_SUCCEEDED: 'SIGN_IN_SUCCEEDED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    // Sign Out
    SIGN_OUT_SUCCEEDED: 'SIGN_OUT_SUCCEEDED',
    SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
    // Sign Up
    SIGN_UP_SUCCEEDED: 'SIGN_UP_SUCCEEDED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    // Get current user
    GET_CURRENT_SUCCEEDED: "GET_CURRENT_SUCCEEDED",
    GET_CURRENT_FAILED: "GET_CURRENT_FAILED",
    // Set User State
    SET_USER: 'SET_USER',
    CLEAR_USER_TOKEN: 'CLEAR_USER_TOKEN',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    //Get Product 
    GET_PRODUCT_SUCCEEDED: 'GET_PRODUCT_SUCCEEDED',
    GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED',
};
